
name: deploy github|gitee pages

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - develop

jobs:
  deploy-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 当前分支
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: 构建静态文件
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 推送到 master
        uses: JamesIves/github-pages-deploy-action@v4
        # 环境变量 注意在 Settings->Secrets 配置 PERSONAL_WORKFLOW_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_WORKFLOW_TOKEN }}
        with:
          # 这是文档部署到的分支名称
          branch: master
          folder: src/.vuepress/dist
